### YamlMime:ManagedReference
items:
- uid: QuickKit.Configuration
  commentId: N:QuickKit.Configuration
  id: QuickKit.Configuration
  children:
  - QuickKit.Configuration.KitConfiguration
  langs:
  - csharp
  - vb
  name: QuickKit.Configuration
  nameWithType: QuickKit.Configuration
  fullName: QuickKit.Configuration
  type: Namespace
  assemblies:
  - QuickKit
references:
- uid: QuickKit.Configuration.KitConfiguration
  commentId: T:QuickKit.Configuration.KitConfiguration
  href: QuickKit.Configuration.KitConfiguration.html
  name: KitConfiguration
  nameWithType: KitConfiguration
  fullName: QuickKit.Configuration.KitConfiguration
