### YamlMime:ManagedReference
items:
- uid: QuickKit.Configuration.KitConfiguration
  commentId: T:QuickKit.Configuration.KitConfiguration
  id: KitConfiguration
  parent: QuickKit.Configuration
  children:
  - QuickKit.Configuration.KitConfiguration.AddQuickKit(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String,System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler})
  langs:
  - csharp
  - vb
  name: KitConfiguration
  nameWithType: KitConfiguration
  fullName: QuickKit.Configuration.KitConfiguration
  type: Class
  source:
    remote:
      path: QuickKit/Configuration/KitConfiguration.cs
      branch: docs
      repo: https://github.com/VictorSantos09/QuickKit.git
    id: KitConfiguration
    path: QuickKit/Configuration/KitConfiguration.cs
    startLine: 8
  assemblies:
  - QuickKit
  namespace: QuickKit.Configuration
  summary: Provides extension methods for configuring QuickKit.
  example: []
  syntax:
    content: public static class KitConfiguration
    content.vb: Public Module KitConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: QuickKit.Configuration.KitConfiguration.AddQuickKit(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String,System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler})
  commentId: M:QuickKit.Configuration.KitConfiguration.AddQuickKit(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String,System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler})
  id: AddQuickKit(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String,System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler})
  isExtensionMethod: true
  parent: QuickKit.Configuration.KitConfiguration
  langs:
  - csharp
  - vb
  name: AddQuickKit(IServiceCollection, string, Func<IDatabaseConnectionHandler>?)
  nameWithType: KitConfiguration.AddQuickKit(IServiceCollection, string, Func<IDatabaseConnectionHandler>?)
  fullName: QuickKit.Configuration.KitConfiguration.AddQuickKit(Microsoft.Extensions.DependencyInjection.IServiceCollection, string, System.Func<QuickKit.Shared.Handlers.IDatabaseConnectionHandler>?)
  type: Method
  source:
    remote:
      path: QuickKit/Configuration/KitConfiguration.cs
      branch: docs
      repo: https://github.com/VictorSantos09/QuickKit.git
    id: AddQuickKit
    path: QuickKit/Configuration/KitConfiguration.cs
    startLine: 17
  assemblies:
  - QuickKit
  namespace: QuickKit.Configuration
  summary: Adds QuickKit services to the specified <xref href="Microsoft.Extensions.DependencyInjection.IServiceCollection" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static IServiceCollection AddQuickKit(this IServiceCollection services, string connectionString, Func<IDatabaseConnectionHandler>? config = null)
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
      description: The <xref href="Microsoft.Extensions.DependencyInjection.IServiceCollection" data-throw-if-not-resolved="false"></xref> to add the services to.
    - id: connectionString
      type: System.String
      description: The connection string to use for the database.
    - id: config
      type: System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler}
      description: An optional configuration function to customize the database connection handler.
    return:
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
      description: The modified <xref href="Microsoft.Extensions.DependencyInjection.IServiceCollection" data-throw-if-not-resolved="false"></xref>.
    content.vb: Public Shared Function AddQuickKit(services As IServiceCollection, connectionString As String, config As Func(Of IDatabaseConnectionHandler) = Nothing) As IServiceCollection
  overload: QuickKit.Configuration.KitConfiguration.AddQuickKit*
  nameWithType.vb: KitConfiguration.AddQuickKit(IServiceCollection, String, Func(Of IDatabaseConnectionHandler))
  fullName.vb: QuickKit.Configuration.KitConfiguration.AddQuickKit(Microsoft.Extensions.DependencyInjection.IServiceCollection, String, System.Func(Of QuickKit.Shared.Handlers.IDatabaseConnectionHandler))
  name.vb: AddQuickKit(IServiceCollection, String, Func(Of IDatabaseConnectionHandler))
references:
- uid: QuickKit.Configuration
  commentId: N:QuickKit.Configuration
  href: QuickKit.html
  name: QuickKit.Configuration
  nameWithType: QuickKit.Configuration
  fullName: QuickKit.Configuration
  spec.csharp:
  - uid: QuickKit
    name: QuickKit
    href: QuickKit.html
  - name: .
  - uid: QuickKit.Configuration
    name: Configuration
    href: QuickKit.Configuration.html
  spec.vb:
  - uid: QuickKit
    name: QuickKit
    href: QuickKit.html
  - name: .
  - uid: QuickKit.Configuration
    name: Configuration
    href: QuickKit.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  commentId: T:Microsoft.Extensions.DependencyInjection.IServiceCollection
  parent: Microsoft.Extensions.DependencyInjection
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
- uid: QuickKit.Configuration.KitConfiguration.AddQuickKit*
  commentId: Overload:QuickKit.Configuration.KitConfiguration.AddQuickKit
  href: QuickKit.Configuration.KitConfiguration.html#QuickKit_Configuration_KitConfiguration_AddQuickKit_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_String_System_Func_QuickKit_Shared_Handlers_IDatabaseConnectionHandler__
  name: AddQuickKit
  nameWithType: KitConfiguration.AddQuickKit
  fullName: QuickKit.Configuration.KitConfiguration.AddQuickKit
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler}
  commentId: T:System.Func{QuickKit.Shared.Handlers.IDatabaseConnectionHandler}
  parent: System
  definition: System.Func`1
  href: https://learn.microsoft.com/dotnet/api/system.func-1
  name: Func<IDatabaseConnectionHandler>
  nameWithType: Func<IDatabaseConnectionHandler>
  fullName: System.Func<QuickKit.Shared.Handlers.IDatabaseConnectionHandler>
  nameWithType.vb: Func(Of IDatabaseConnectionHandler)
  fullName.vb: System.Func(Of QuickKit.Shared.Handlers.IDatabaseConnectionHandler)
  name.vb: Func(Of IDatabaseConnectionHandler)
  spec.csharp:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: <
  - uid: QuickKit.Shared.Handlers.IDatabaseConnectionHandler
    name: IDatabaseConnectionHandler
    href: QuickKit.Shared.Handlers.IDatabaseConnectionHandler.html
  - name: '>'
  spec.vb:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: (
  - name: Of
  - name: " "
  - uid: QuickKit.Shared.Handlers.IDatabaseConnectionHandler
    name: IDatabaseConnectionHandler
    href: QuickKit.Shared.Handlers.IDatabaseConnectionHandler.html
  - name: )
- uid: Microsoft.Extensions.DependencyInjection
  commentId: N:Microsoft.Extensions.DependencyInjection
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.DependencyInjection
  nameWithType: Microsoft.Extensions.DependencyInjection
  fullName: Microsoft.Extensions.DependencyInjection
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection
- uid: System.Func`1
  commentId: T:System.Func`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.func-1
  name: Func<TResult>
  nameWithType: Func<TResult>
  fullName: System.Func<TResult>
  nameWithType.vb: Func(Of TResult)
  fullName.vb: System.Func(Of TResult)
  name.vb: Func(Of TResult)
  spec.csharp:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Func`1
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
